<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Account_fa fa-angle-down text-primary</name>
   <tag></tag>
   <elementGuidId>7f494159-1ea1-486c-acc9-21faeb7df19b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-angle-down.text-primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='account-dropdown']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-angle-down text-primary</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;h-100 js&quot;]/body[@class=&quot;customer-logged-in template-customersaccount ng-scope&quot;]/header[@class=&quot;d-none d-md-block&quot;]/nav[@class=&quot;border-top border-primary border-4 small&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-4 text-right&quot;]/div[@class=&quot;navbar-text ng-scope&quot;]/ul[@class=&quot;list-inline list-divider m-0&quot;]/li[@class=&quot;list-inline-item&quot;]/vc-account-switch-migration[@class=&quot;d-inline-block ng-isolate-scope&quot;]/div[@class=&quot;dropdown account-switch&quot;]/a[@id=&quot;account-dropdown&quot;]/i[@class=&quot;fa fa-angle-down text-primary&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='account-dropdown']/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
   </webElementXpaths>
</WebElementEntity>
